### ISSUE TITLE
No cabal found

### ISSUE THREAD

**Issue by carliros** [haskell-servant/example-servant-elm#1]
Hello, i'm having this error when running make:

`````
$ make
(cd client ; elm package install -y)
Packages configured successfully!
stack setup
stack will use a locally installed GHC
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
stack test --only-dependencies
No .cabal file found in directory /project-path/example-servant-elm/
make: *** [server-setup] Error 1
`````

don't we need a cabal for the haskell package to use stack?

**Comment by soenkehahn** [comment]
`stack` has the feature to generate the cabal file on the fly (through `hpack`) since some time. Looks like you're using an older version of `stack`. So I'd recommend you update your `stack` version. (Not only for this reason.)

I'll add the cabal file to the repo however. Maybe someone wants to build this with cabal.

**Comment by soenkehahn** [comment]
Done.

**Comment by carlos-gomez-tx** [comment]
thx
